CREATE TABLE book (
                      id bigint GENERATED BY DEFAULT AS IDENTITY,
                      title varchar(255),
                      author varchar(255),
                      price double precision,
                      description varchar(1000),
                      coverPhotoUrl varchar(255),
                      available boolean,
                      primary key (id)
);

CREATE TABLE comment (
                         id bigint GENERATED BY DEFAULT AS IDENTITY,
                         user varchar(255),
                         text varchar(1000),
                         book_id bigint,
                         primary key (id),
                         foreign key (book_id) references book
);
